Repository Anamaya1729/JavaScript-Basic-Projects, pull requests merged in 2022-10, with the labels that each got.

#13 code for classic snake game
  medium/snake-game/index.html
  medium/snake-game/snake.js
Labels: hacktoberfest-accepted

#36 Added Infinite Scroll
  medium/infinite_scroll/README.md
  medium/infinite_scroll/index.html
  medium/infinite_scroll/loader.svg
  medium/infinite_scroll/script.js
  medium/infinite_scroll/style.css
Labels: hacktoberfest-accepted

#40 Dictionary App
  medium/dictionary_app/README.md
  medium/dictionary_app/app.js
  medium/dictionary_app/index.html
  medium/dictionary_app/script.js
  medium/dictionary_app/style.css
Labels: hacktoberfest-accepted

#28 Added Dice Predicting Game
  easy/dice-game/README.md
  easy/dice-game/app.js
  easy/dice-game/background.jfif
  easy/dice-game/index.html
  easy/dice-game/style.css
Labels: hacktoberfest-accepted

#24 Added easy project form_validation
  easy/form_validation/README.md
  easy/form_validation/css/style.css
  easy/form_validation/css/sweetalert2.min.css
  easy/form_validation/index.html
  easy/form_validation/js/jquery-3.0.0.min.js
  easy/form_validation/js/script.js
  easy/form_validation/js/sweetalert2.min.js
Labels: hacktoberfest-accepted

#42 Added a GithubFinder project in the medium folder
  medium/GitHub_Finder/README.md
  medium/GitHub_Finder/app.js
  medium/GitHub_Finder/bootstrap.min.css
  medium/GitHub_Finder/bootstrap2.min.css
  medium/GitHub_Finder/bootstrap3.min.css
  medium/GitHub_Finder/example.png
  medium/GitHub_Finder/github.js
  medium/GitHub_Finder/index.html
  medium/GitHub_Finder/ui.js
Labels: hacktoberfest-accepted

#43 📦 NEW: random color generator
  easy/README.md
  easy/random-color-generator/README.md
  easy/random-color-generator/app.js
  easy/random-color-generator/index.html
Labels: hacktoberfest-accepted

#48 FeedBackPage
  easy/feedback_page/README.md
  easy/feedback_page/index.html
  easy/feedback_page/logic.js
  easy/feedback_page/readme.md
  easy/feedback_page/style.css
Labels: hacktoberfest-accepted

#45 Color Palette Faraz
  easy/Color Scheme Generator/.vscode/settings.json
  easy/Color Scheme Generator/Readme.md
  easy/Color Scheme Generator/color-pallete.png
  easy/Color Scheme Generator/images/color-pallete.png
  easy/Color Scheme Generator/index.css
  easy/Color Scheme Generator/index.html
  easy/Color Scheme Generator/index.js
Labels: hacktoberfest-accepted

#59 tic tac toe
  easy/tic_tac_toe/README.md
  easy/tic_tac_toe/app.js
  easy/tic_tac_toe/index.html
  easy/tic_tac_toe/sounds/gameover.mp3
  easy/tic_tac_toe/sounds/ting.mp3
  easy/tic_tac_toe/style.css
Labels: hacktoberfest-accepted

#63 Countdown timer added
  easy/countown_with_timer/app.js
  easy/countown_with_timer/images/bg.mp4
  easy/countown_with_timer/images/favicon.png
  easy/countown_with_timer/index.html
  easy/countown_with_timer/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#71 feature/analog-clock
  medium/analog_clock/app.js
  medium/analog_clock/images/README.md
  medium/analog_clock/images/clock.png
  medium/analog_clock/index.html
  medium/analog_clock/style.css
Labels: hacktoberfest-accepted

#72 rock-paper-scissor developed
  easy/rock_paper_scissor/app.js
  easy/rock_paper_scissor/images/1.png
  easy/rock_paper_scissor/images/2.png
  easy/rock_paper_scissor/images/3.png
  easy/rock_paper_scissor/images/4.png
  easy/rock_paper_scissor/index.html
  easy/rock_paper_scissor/style.css
Labels: hacktoberfest-accepted

#75 created the tip calculator
  easy/tip_calculator/README.md
  easy/tip_calculator/index.html
  easy/tip_calculator/script.js
  easy/tip_calculator/style.css
Labels: hacktoberfest-accepted

#74 Color picker and Switcher Project
  easy/color_picker_and_switcher/README.md
  easy/color_picker_and_switcher/app.js
  easy/color_picker_and_switcher/index.html
  easy/color_picker_and_switcher/style.css
Labels: hacktoberfest-accepted

#77 added currency converter
  easy/currency_convertor/app.js
  easy/currency_convertor/index.html
  easy/currency_convertor/style.css
Labels: hacktoberfest-accepted

#73 text editor added under hacktoberfest 2022
  easy/text_editor/README.md
  easy/text_editor/index.css
  easy/text_editor/index.html
  easy/text_editor/index.js
Labels: hacktoberfest-accepted

#86 gst calculator added
  easy/GSTCalculator/.gitattributes
  easy/GSTCalculator/README.md
  easy/GSTCalculator/favicon.ico
  easy/GSTCalculator/img/android-chrome-192x192.png
  easy/GSTCalculator/img/android-chrome-512x512.png
  easy/GSTCalculator/img/apple-touch-icon.png
  easy/GSTCalculator/img/favicon-16x16.png
  easy/GSTCalculator/img/favicon-32x32.png
  easy/GSTCalculator/index.html
  easy/GSTCalculator/script.js
  easy/GSTCalculator/site.webmanifest
  easy/GSTCalculator/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#97 I have developed a cool car simulation, A medium level project.
  medium/car-simulation/car.js
  medium/car-simulation/car.png
  medium/car-simulation/controls.js
  medium/car-simulation/index.html
  medium/car-simulation/main.js
  medium/car-simulation/network.js
  medium/car-simulation/readme.md
  medium/car-simulation/road.js
  medium/car-simulation/sensor.js
  medium/car-simulation/style.css
  medium/car-simulation/utils.js
  medium/car-simulation/visualizer.js
Labels: hacktoberfest-accepted, hacktoberfest

#90 Added Animated Search Bar Project
  .vscode/settings.json
  easy/Animated_SearchBar/README.md
  easy/Animated_SearchBar/app.js
  easy/Animated_SearchBar/index.html
  easy/Animated_SearchBar/preview.png
  easy/Animated_SearchBar/style.css
Labels: invalid

#103 Added the flex panel project
  easy/Flex-Panel/README.md
  easy/Flex-Panel/app.js
  easy/Flex-Panel/index.html
  easy/Flex-Panel/style.css
Labels: hacktoberfest-accepted

#113 Added Marvel App
  medium/Marvel App/App.js
  medium/Marvel App/README.md
  medium/Marvel App/assets/background.jpg
  medium/Marvel App/assets/loading.gif
  medium/Marvel App/character-names.js
  medium/Marvel App/index.html
  medium/Marvel App/styles.css
Labels: hacktoberfest-accepted

#116 Added the live css update project
  easy/CssLiveUpdate/README.md
  easy/CssLiveUpdate/app.js
  easy/CssLiveUpdate/index.html
  easy/CssLiveUpdate/style.css
Labels: hacktoberfest-accepted

#124 feature/drum-kit
  medium/Drum-Kit/README.md
  medium/Drum-Kit/images/Capture.PNG
  medium/Drum-Kit/images/crash.png
  medium/Drum-Kit/images/kick.png
  medium/Drum-Kit/images/snare.png
  medium/Drum-Kit/images/tom1.png
  medium/Drum-Kit/images/tom2.png
  medium/Drum-Kit/images/tom3.png
  medium/Drum-Kit/images/tom4.png
  medium/Drum-Kit/index.html
  medium/Drum-Kit/index.js
  medium/Drum-Kit/sounds/crash.mp3
  medium/Drum-Kit/sounds/kick-bass.mp3
  medium/Drum-Kit/sounds/snare.mp3
  medium/Drum-Kit/sounds/tom-1.mp3
  medium/Drum-Kit/sounds/tom-2.mp3
  medium/Drum-Kit/sounds/tom-3.mp3
  medium/Drum-Kit/sounds/tom-4.mp3
  medium/Drum-Kit/styles.css
Labels: hacktoberfest-accepted

#99 I have built a typing speed calculator using vanilla js
  easy/TypingSpeedCalculator/index.html
  easy/TypingSpeedCalculator/octopus.png
  easy/TypingSpeedCalculator/readme.md
  easy/TypingSpeedCalculator/script.js
  easy/TypingSpeedCalculator/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#136 project is about e-commerce store
  hard/ComfyStore/README.md
  hard/ComfyStore/about.html
  hard/ComfyStore/images/logo-black.svg
  hard/ComfyStore/images/logo-white.svg
  hard/ComfyStore/images/main-bcg.jpeg
  hard/ComfyStore/index.html
  hard/ComfyStore/index.js
  hard/ComfyStore/product.html
  hard/ComfyStore/products.html
  hard/ComfyStore/readme.md
  hard/ComfyStore/src/cart/addToCartDOM.js
  hard/ComfyStore/src/cart/setupCart.js
  hard/ComfyStore/src/cart/toggleCart.js
  hard/ComfyStore/src/displayProducts.js
  hard/ComfyStore/src/fetchProducts.js
  hard/ComfyStore/src/filters/companies.js
  hard/ComfyStore/src/filters/price.js
  hard/ComfyStore/src/filters/search.js
  hard/ComfyStore/src/pages/about.js
  hard/ComfyStore/src/pages/product.js
  hard/ComfyStore/src/pages/products.js
  hard/ComfyStore/src/store.js
  hard/ComfyStore/src/toggleSidebar.js
  hard/ComfyStore/src/utils.js
  hard/ComfyStore/styles.css
Labels: hacktoberfest-accepted
